services:
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "test", "$(redis-cli PING) = PONG"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      start_interval: 1s
    command: ["redis-server", "--appendonly yes"]
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pg_root
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d neocities -U postgres" ]
      interval: 30s
      timeout: 10s
      start_period: 60s
      start_interval: 1s
    volumes:
      - ./docker/pg_setup.sh:/docker-entrypoint-initdb.d/pg_setup.sh
  sidekiq:
    build:
      dockerfile: docker/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./:/app:ro
      - public:/public
    working_dir: /app
    command: bundle exec sidekiq -r ./environment.rb
  screenjesus:
    build:
      context: ./docker/screenjesus
      dockerfile: ../Dockerfile
    volumes:
      - ./docker/screenjesus:/app:ro
    working_dir: /app
    cap_add: ["SYS_ADMIN"] # https://github.com/jessfraz/dockerfiles/issues/65#issuecomment-145731454
    entrypoint: bundle exec ruby pup.rb -o 0.0.0.0
  nginx:
    build:
      dockerfile: Dockerfile-nginx
      context: ./docker
    ports:
      - 9292:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - public:/usr/share/nginx/html/neocities:ro
      - nginx_logs:/etc/nginx/logs
  main:
    build:
      dockerfile: docker/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
      - public:/public
    working_dir: /app
    entrypoint: bundle exec rackup -o 0.0.0.0

volumes:
  nginx_logs:
  public:
