FROM nginx

RUN userdel -r nginx

ARG USERNAME=nginx
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN chown -R $USER_UID /etc/nginx/
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME -r -G audio,video
